AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Lambdas that are deployed

Parameters:
  BucketName:
    Type: String
    Default: dev-blog-metrics
    Description: Name of the s3 bucket

Resources:
  PersistMetricsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumedRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - 'sts:AssumeRole'
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource: !Sub 'arn:aws:s3:::${BucketName}/*'
          - Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource: !Sub 'arn:aws:s3:::${BucketName}'

  PersistMetricsLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: 
        ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.eu-west-1.amazonaws.com/dev-blog/persist-metrics-lambda:latest
      Environment:
        Variables:
          S3_BUCKET: !Ref BucketName
          REGION: !Ref AWS::Region
      FunctionName: persist-metrics-lambda
      Role: !Ref PersistMetricsLambdaRole
      Timeout: 10

