name: persist-metrics

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: |-
          cd persist-metrics-lambda
          npm ci
          npm run build --if-present
          npm test
    env:
      CI: true
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: kciter/aws-ecr-action@master
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: dev-blog/persist-metrics-lambda
        region: eu-west-1
        tags: latest
        path: './persist-metrics-lambda/'
        create_repo: false
        set_repo_policy: false
