name: persist-metrics

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - run: |-
          cd persist-metrics-lambda
          npm ci
          npm run build --if-present
          npm test
    env:
      CI: true
